spring.application.name=shop
server.port=8080
spring.profiles.active=dev
spring.main.banner-mode=off

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.username=shop_owner
spring.datasource.password=ownerPass@123
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security
spring.security.user.name=admin
spring.security.user.password=admin